### ISSUE TITLE
Incorrect exit code when tests fail

### ISSUE THREAD

**Issue by vmcruz** [browserstack/browserstack-cypress-cli#285]
Whenever tests from cypress fail, I'd expect the exit code to be different than 0. Right now I'm getting success whether the tests fail or not. For instance:

```
Total tests: 37, passed: 34, failed: 3, skipped: 0
Done in 2856.008 seconds using 10 machines
```

It was reported as success. I'm currently using v1.13 with Cypress 9.4.1, but this happened with v1.12.1 and Cypress 8.7.1. Not sure if this is intended, but it doesn't feel correct for a CI tool.

Noticing this issue from 1.10 all the way through 1.13 (not sure if this was previously present). It might be worth mentioning that I'm using 10 machines with the parallel support.

Probably related to https://github.com/browserstack/browserstack-cypress-cli/issues/170

**Comment by SachinMNair** [comment]
Hey Victor,

Thank you for raising this issue. We got it checked from our engineering team but they were not able to reproduce the issue that you have reported, attaching a screenshot for your reference.

Could you please raise a support ticket by dropping an email to **support@browserstack.com** and share the build ID for which you are facing this issue so that we can check it from our end?
![Screenshot 2022-03-24 at 11 50 55 AM](https://user-images.githubusercontent.com/88542507/160014148-276354d4-f06a-4126-b52f-a56849335af2.png)

**Comment by vmcruz** [comment]
Oh gosh, this might be an issue within my script then. I'll run some tests and get back to you with my findings. I wrongly assumed this was related to that other issue with the exit codes. I'll close it for now and reopen if needed.

Thank you for the quick help.
